export const accountConstant = {
    SET_PRIVATE_PUBLIC_KEY: 'SET_PRIVATE_PUBLIC_KEY',
    UPDATE_USERNAME: 'UPDATE_USERNAME',
    UPDATE_EMAIL: 'UPDATE_EMAIL',
    UPDATE_AVATAR: 'UPDATE_AVATAR',
    SET_PROFILE_USER: 'SET_PROFILE_USER',
    SET_BALANCE: 'SET_BALANCE',
    SET_OXYGEN: 'SET_OXYGEN',
    SET_NUMBER_POST: 'SET_NUMBER_POST',
    SET_NUMBER_FOLLOWING: 'SET_NUMBER_FOLLOWING',
    SET_NUMBER_FOLLOWERS: 'SET_NUMBER_FOLLOWERS',
    SET_PROFILE: 'SET_PROFILE'
}
