export const headerMainConstant = {
    SET_ITEM_HEADER_MAIN_SELETED: "SET_ITEM_HEADER_MAIN_SELETED",
    IS_SEND_MONEY_SUCCESS: "IS_SEND_MONEY_SUCCESS",
    IS_UPDATE_NAME_SUCCESS: 'IS_UPDATE_NAME_SUCCESS',
    IS_UPDATE_EMAIL_SUCCESS: 'IS_UPDATE_EMAIL_SUCCESS'
}
